name: race_calculator_2
description: "Race Calculator 2 - приложение для расчета результатов рейса и аналитики."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  intl: ^0.19.0
  uuid: ^4.3.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  # Android дополнительно (опционально):
  adaptive_icon_background: "#FFFFFF" # фон для адаптивной иконки
  adaptive_icon_foreground: "assets/icon.png" # передний план
